DROP TABLE IF EXISTS sisi.factor_all_stop_events;
CREATE TABLE sisi.factor_all_stop_events (
     event_id VARCHAR(255) PRIMARY KEY,
     mmsi INT,
     mmsi_cate VARCHAR(255),
     ship_name VARCHAR(255),
     imo VARCHAR(255),
     begin_time BIGINT,
     end_time BIGINT,
     begin_year INT,
     begin_month INT,
     begin_day INT,
     begin_lng FLOAT,
     begin_lat FLOAT,
     end_lng FLOAT,
     end_lat FLOAT,
     middle_lng FLOAT,
     middle_lat FLOAT,
     avg_lng FLOAT,
     avg_lat FLOAT,
     middle_hdg FLOAT,
     max_hdg FLOAT,
     min_hdg FLOAT,
     middle_sog FLOAT,
     max_sog FLOAT,
     middle_cog FLOAT,
     max_cog FLOAT,
     min_cog FLOAT,
     max_rot FLOAT,
     min_rot FLOAT,
     middle_rot FLOAT,
     point_num INT,
     avg_speed FLOAT,
     avg_steady_speed FLOAT,
     sailing_distance FLOAT,
     zone_id INT,
     navistate VARCHAR(255),
     now_port_name VARCHAR(255),
     now_port_id INT,
     now_dock_name VARCHAR(255),
     now_dock_id INT,
     now_berth_name VARCHAR(255),
     now_berth_id INT,
     coal_dock_id INT,
     now_port_lng FLOAT,
     now_port_lat FLOAT,
     event_categories VARCHAR(255),
     province VARCHAR(255),
     country VARCHAR(255),
     event_cate VARCHAR(255),
     INDEX idx_common (mmsi, begin_time, end_time, avg_speed, zone_id)
);